<a href="https://colab.research.google.com/github/subhamsam007/Numpy-and-pandas/blob/main/practice_project_countries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# data capstone project
of all countries

In [73]:
import pandas as pd
import numpy as np

In [74]:
df =pd.read_csv('Countries.csv')

In [75]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [76]:
df.shape

(194, 64)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [78]:
df.describe().round()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.0,194.0,193.0,194.0,194.0,194.0,194.0,120.0,156.0,1.930000e+02,...,194.0,194.0,194.0,1.940000e+02,193.0,194.0,194.0,194.0,194.0,194.0
mean,19.0,22.0,245455.0,208678.0,667509.0,656371.0,9777.0,67.0,30.0,5.144851e+11,...,-51.0,20283160.0,20505718.0,4.078888e+07,25.0,17633220.0,23155658.0,3.0,5.0,26.0
std,24.0,66.0,635627.0,782493.0,1837107.0,1811169.0,42301.0,72.0,27.0,2.307148e+12,...,94526.0,72589408.0,76071584.0,1.486470e+08,13.0,76641875.0,79403935.0,2.0,3.0,9.0
min,-41.0,-175.0,4.0,0.0,2.0,0.0,0.0,0.0,0.0,6.034940e+07,...,-525116.0,5513.0,5799.0,1.131200e+04,0.0,0.0,5717.0,0.0,0.0,10.0
25%,4.0,-5.0,6464.0,3332.0,23552.0,21866.0,360.0,32.0,18.0,1.181390e+10,...,-12242.0,1036218.0,1044902.0,2.106358e+06,15.0,589664.0,1222244.0,2.0,3.0,17.0
50%,17.0,22.0,38728.0,25289.0,120375.0,115994.0,1645.0,55.0,27.0,4.115390e+10,...,-970.0,4502713.0,4450049.0,9.125614e+06,25.0,2512382.0,4508837.0,2.0,5.0,25.0
75%,40.0,50.0,215000.0,123674.0,523700.0,491150.0,4054.0,80.0,35.0,2.519450e+11,...,2904.0,15266064.0,14788725.0,3.031361e+07,34.0,11333543.0,16213546.0,3.0,7.0,34.0
max,65.0,178.0,5285080.0,8153120.0,16376900.0,16224200.0,522345.0,688.0,310.0,2.546270e+13,...,561580.0,691528501.0,731180498.0,1.417173e+09,61.0,908804812.0,897578430.0,10.0,10.0,50.0

In [79]:
# find the um of latitude # optional for understanding
sum=df['latitude'].sum()
mean= sum//194
mean

np.float64(18.0)

In [80]:
df.columns   # thi is to check how many colums are there

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

# practice question start from here

In [81]:
# which country has the highest population
Highet_population=df[df['population']== df['population'].max()]['country']
Highet_population

75    India
Name: country, dtype: object

In [82]:
#which country has the least population
least_population=df[df['population']== df['population'].min()][['country', 'population']]
least_population

    country  population
179  Tuvalu       11312

In [83]:
#what is the capital of the country with least population
least_population_capital=df[df['population']== df['population'].min()]['capital_city']
least_population_capital

179    Funafuti
Name: capital_city, dtype: object

In [84]:
#give me top 5 countries with highest democratic score
democratic_score = df.sort_values(by='democracy_score', ascending=False).head(2)["country"]
democratic_score

127     Norway
74     Iceland
Name: country, dtype: object

In [85]:
#how many total regions are there
total_regions = df['region'].value_counts().count()
total_regions

np.int64(22)

In [86]:
#how many countries lie in Eastern Europe region
eastern_europe_countries = df[df['region'] == 'Eastern Europe']['country']
eastern_europe_countries

14             Belarus
24            Bulgaria
43      Czech Republic
73             Hungary
111            Moldova
136             Poland
139            Romania
140             Russia
151    Slovak Republic
181            Ukraine
Name: country, dtype: object

In [87]:
#who is the political leader of the 2nd highest populated country
df[df['population'] == df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

In [88]:
# how many countries are there whoes political leaders are unknown
df[df['political_leader'].isna()]['country']

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: object

In [89]:
#how many country have Republic in their full name **country_long row you havr to take to solve
# this is one shortcut method
df[df['country_long'].str.contains('Republic')]['country']

1        Albania
2        Algeria
4         Angola
6      Argentina
7        Armenia
         ...
187      Vanuatu
189      Vietnam
191        Yemen
192       Zambia
193     Zimbabwe
Name: country, Length: 125, dtype: object

In [90]:
# another method to find
count = 0
def find_republic(txt):
    global count
    if 'republic' in txt.lower():
        count+= 1
    return txt
df['country_long'] = df['country_long'].apply(find_republic)
print(count)

125

In [98]:
#which country in african region has highest population
africa_df = df[df['continent'] == 'Africa']
africa_df[africa_df['population'] == africa_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object